# Generated by Django 4.2.4 on 2023-11-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['id'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
    ]
