# Generated by Django 4.2.4 on 2023-11-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='linked_habits',
            new_name='linked_habit',
        ),
    ]
